name: Update Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update version.json
        run: |
          mkdir -p updates
          echo "{
            \"version\": \"${{ github.sha }}\",
            \"downloadUrl\": \"${{ github.server_url }}/${{ github.repository }}/releases/latest\",
            \"message\": \"Update baru tersedia dengan perbaikan dan peningkatan\"
          }" > updates/version.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add updates/version.json
          git commit -m "Update version info"
          git push
